In [2]:
# !py -3.13 -m pip install torch torchvision --index-url https://download.pytorch.org/whl/cu130
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.1+cu130


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using torch.Tensor()

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 6]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 6]])

## Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at the data -> update random numbers ...`

In [17]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6232, 0.2880, 0.1180, 0.3523],
        [0.3586, 0.3019, 0.6297, 0.7228],
        [0.2718, 0.8791, 0.2223, 0.3081]])

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor, random_image_size_tensor.ndim

(tensor([[[0.7875, 0.2168, 0.3406,  ..., 0.6235, 0.8143, 0.7839],
          [0.6006, 0.7692, 0.6512,  ..., 0.7942, 0.9988, 0.4594],
          [0.8555, 0.7219, 0.4868,  ..., 0.6447, 0.6671, 0.0466],
          ...,
          [0.1579, 0.6783, 0.4375,  ..., 0.1835, 0.2251, 0.7538],
          [0.4312, 0.8015, 0.0145,  ..., 0.0498, 0.4222, 0.1218],
          [0.4985, 0.1605, 0.6380,  ..., 0.6445, 0.3732, 0.0074]],
 
         [[0.3665, 0.5595, 0.4635,  ..., 0.5279, 0.8739, 0.4943],
          [0.9703, 0.8579, 0.0845,  ..., 0.4227, 0.9033, 0.8811],
          [0.1114, 0.8335, 0.2210,  ..., 0.4094, 0.5811, 0.0766],
          ...,
          [0.3832, 0.1224, 0.3137,  ..., 0.4552, 0.5422, 0.5898],
          [0.1689, 0.0163, 0.6887,  ..., 0.9403, 0.9037, 0.0529],
          [0.7118, 0.6144, 0.6291,  ..., 0.6053, 0.4430, 0.6615]],
 
         [[0.5574, 0.4251, 0.4459,  ..., 0.3820, 0.4685, 0.1134],
          [0.2313, 0.3957, 0.2644,  ..., 0.0043, 0.9988, 0.8828],
          [0.5208, 0.8089, 0.4135,  ...,

### Zeros and Ones

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatyes

**Note:** Tensor datatype is one of the 3 big erros you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [24]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatye is the tensor (e.g. flaot32 or float64)
                               device="cuda", # what device is your tensor on
                               requires_grad=False) # whether or not to track gradeints with this tensors operations
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
# type cast float32 tensor to float16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [27]:
float_16_tensor.dtype

torch.float16

In [31]:
(float_16_tensor * float_32_tensor).dtype
(float_16_tensor * float_16_tensor).dtype

torch.float16

In [39]:
int_32_tensor = torch.tensor([3,6,9] , dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [44]:
# ash code
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [53]:
# (float_32_tensor * int_32_tensor) # -> Error (int32 loads in cpu and float32 loads in cpu)
# Fix: load the tensor explicitly into the gpu using .to() method
print(float_32_tensor * int_32_tensor.to(device))
print((float_32_tensor * int_32_tensor.to(device)).dtype)

tensor([ 9., 36., 81.], device='cuda:0')
torch.float32


In [55]:
long_tensor = torch.tensor([3,5,6] , dtype=torch.long, device=device)
print(long_tensor.dtype)

torch.int64


In [71]:
int_32_tensor = int_32_tensor.to(device)
int_32_tensor * long_tensor

tensor([ 9, 30, 54], device='cuda:0')

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [72]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0813, 0.2005, 0.5075, 0.8020],
        [0.9729, 0.5175, 0.2673, 0.4546],
        [0.6726, 0.9769, 0.5313, 0.5964]])

In [73]:
# find out details about some tensor
print(some_tensor)
print(f"Datetype of tensor: {some_tensor.dtype}")
# print(f"Shape of tensor: {some_tensor.size()}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0813, 0.2005, 0.5075, 0.8020],
        [0.9729, 0.5175, 0.2673, 0.4546],
        [0.6726, 0.9769, 0.5313, 0.5964]])
Datetype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# create a tensor
tensor = torch.tensor([1,2,3])
# add tensor by 10
tensor + 10

tensor([11, 12, 13])

In [75]:
# multply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [76]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [77]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [78]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main ruless that performing matrix multiplication needs to satisfy
1. The **inner dimensions** must match:
    * `(3, 2) @ (3, 2)` won't work
    * `(2, 3) @ (3, 2)` will work
    * `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
    * `(2, 3) @ (3, 2) -> (2, 2)`
    * `(3, 2) @ (2, 3) -> (3, 3)`

In [104]:
print(torch.matmul(torch.rand(2, 3), torch.rand(3, 2)))
print(torch.matmul(torch.rand(3, 2), torch.rand(2, 3)))
print(torch.matmul(torch.rand(3, 2), torch.rand(3, 2))) # error code

tensor([[0.1954, 0.3500],
        [0.7682, 0.8542]])
tensor([[1.1828, 1.3134, 0.9602],
        [1.2339, 1.3106, 0.7366],
        [0.6133, 0.7546, 0.8252]])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [82]:
# element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multplication
torch.matmul(tensor, tensor)

tensor(14)

In [99]:
tensor @ tensor # same a torch.matmul()

tensor(14)

In [96]:
%%time
# matrix multiplication by hand

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 812 μs


In [97]:
%%time
# faster built-in method
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 71.8 μs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [105]:
# shapes for matrix multiplications
tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_b = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_a, tensor_b) # torch.mm() is the same as torch.matmul() (it's an alias for writing less code)
torch.matmul(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [108]:
tensor_a.shape, tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [114]:
tensor_b, tensor_b.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [118]:
tensor_b.T, tensor_b.T.shape # .T returns transpose of the tensor

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [127]:
# The matrix multiplication operation works when tensor_b is transposed
print(f"Original shapes: tensor_a = {tensor_a.shape}, tensor_b = {tensor_b.shape}")
print(f"New shapes: tensor_a = {tensor_a.shape}, tensor_b = {tensor_b.T.shape}")
print(f"Multiplying: {tensor_a.shape } @ {tensor_b.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_a, tensor_b.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_a = torch.Size([3, 2]), tensor_b = torch.Size([3, 2])
New shapes: tensor_a = torch.Size([3, 2]), tensor_b = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [147]:
# create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [130]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [131]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [141]:
# find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
print(x.dtype)
torch.mean(x.to(torch.float32)), x.type(torch.float32).mean()

torch.int64


(tensor(45.), tensor(45.))

In [142]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max


In [148]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [149]:
# Find the position in tensor that has minimum value with argmin() -> returns the index positon of traget tensor where the minimum value occurs
x.argmin()

tensor(0)

In [150]:
x[0]

tensor(1)

In [151]:
# Find the position in tensor that has minimum value with argmin()
x.argmax()

tensor(9)

In [152]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* **Reshaping** - reshapes an input tensor to a defined shape
* **View** - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* **Stacking** - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* **Squeeze** - removes all `1` dimensions from a tensor
* **Unsqueeze** - add a `1` dimensions to a target tensor
* **Permute** - Return a view of the input with dimensions permuted (swapped) in a certain way

In [184]:
# let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [185]:
# add an extra dimension
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [186]:
# change the view
z = x.view(1, 9)
z, x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [187]:
# changing z changes x (because a view of a tensor shares teh same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [191]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [196]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"\nNew shape: {x_squeezed.shape}")


Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])


In [203]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")


Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

New shape: torch.Size([9, 1])


In [206]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# premute the original tensor to rearranege the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [210]:
x_original[0][0][0], x_original[0, 0, 0]

(tensor(0.6586), tensor(0.6586))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [211]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [212]:
# let's index on our new tensir
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [214]:
# let's index on the middle bracket (dim=1)
x[0, 0], x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [215]:
# let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [216]:
# you can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [218]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [219]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [220]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library

And becaue of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [224]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [227]:
# change the value of array, what will this do to "tensor"?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [228]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [229]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better represenations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does the "flavour" the randomness

In [237]:
import torch

# create two random tensors
random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)

print(random_tensor_a)
print(random_tensor_b)
print((random_tensor_a == random_tensor_b))

tensor([[0.9100, 0.7865, 0.4418, 0.2842],
        [0.8675, 0.6191, 0.5713, 0.5713],
        [0.6508, 0.5179, 0.3889, 0.2502]])
tensor([[0.2464, 0.9473, 0.0636, 0.3743],
        [0.2753, 0.6629, 0.2945, 0.5573],
        [0.6313, 0.9816, 0.1771, 0.7790]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [251]:
# let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3, 4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU. (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's a lots of options...
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little but of setting up, to do this, refer PyTorch setup Documentation https://pytorch.org/get-started/locally/

In [253]:
!nvidia-smi

Tue Dec  2 19:36:33 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.80                 Driver Version: 581.80         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4050 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   53C    P8              3W /   80W |    1126MiB /   6141MiB |     16%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [254]:
# check fro gpu access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://docs.pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if availabe, else default to CPU

In [255]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [256]:
# count the number devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want out tensors/models on the GPU is because using a GPU results in faster computations

In [257]:
# create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [258]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [260]:
# If tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [261]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [262]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')