In [2]:
# !py -3.13 -m pip install torch torchvision --index-url https://download.pytorch.org/whl/cu130
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.1+cu130


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using torch.Tensor()

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as Python int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 6]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 6]])

## Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at the data -> update random numbers ...`

In [20]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8526, 0.4104, 0.0570, 0.3835],
        [0.5972, 0.6764, 0.3199, 0.6660],
        [0.7079, 0.9216, 0.6145, 0.7398]])

In [27]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor, random_image_size_tensor.ndim

(tensor([[[0.1740, 0.9058, 0.6347,  ..., 0.1739, 0.4389, 0.0885],
          [0.1645, 0.8511, 0.5233,  ..., 0.1896, 0.2197, 0.3643],
          [0.2596, 0.8243, 0.4732,  ..., 0.2545, 0.6923, 0.0338],
          ...,
          [0.1251, 0.1737, 0.9372,  ..., 0.4036, 0.0772, 0.0994],
          [0.3473, 0.2748, 0.4098,  ..., 0.3908, 0.8892, 0.0392],
          [0.4603, 0.2894, 0.9506,  ..., 0.7255, 0.8398, 0.8387]],
 
         [[0.7462, 0.7406, 0.8776,  ..., 0.7724, 0.3939, 0.7503],
          [0.8917, 0.4691, 0.1848,  ..., 0.9470, 0.4409, 0.5212],
          [0.1234, 0.1644, 0.7730,  ..., 0.2374, 0.2191, 0.6006],
          ...,
          [0.4805, 0.0335, 0.8060,  ..., 0.8283, 0.6527, 0.5952],
          [0.9832, 0.7707, 0.0418,  ..., 0.8718, 0.5006, 0.8413],
          [0.7375, 0.4885, 0.7245,  ..., 0.7208, 0.9992, 0.3329]],
 
         [[0.5261, 0.1245, 0.8475,  ..., 0.6870, 0.2628, 0.2977],
          [0.5582, 0.4965, 0.7016,  ..., 0.0947, 0.7302, 0.9592],
          [0.4863, 0.2346, 0.9875,  ...,

### Zeros and Ones

In [28]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [39]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatyes

**Note:** Tensor datatype is one of the 3 big erros you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [54]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatye is the tensor (e.g. flaot32 or float64)
                               device="cuda", # what device is your tensor on
                               requires_grad=False) # whether or not to track gradeints with this tensors operations
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [55]:
float_32_tensor.dtype

torch.float32

In [59]:
# type cast float32 tensor to float16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [58]:
float_16_tensor.dtype

torch.float16